### ISSUE TITLE
tarsgo 好像不能使用 http middleware？

### ISSUE THREAD

**Issue by Clark-zhang** [TarsCloud/TarsGo#100]
tars.AddHttpServant() 的第一个参数是 TarsHttpMux struct
所以好像不能使用像 Alice - https://github.com/justinas/alice
或者 gorilla - https://github.com/gorilla/mux
这种middleware？

能改成interface吗？这样用户可以定制自己的TarsHttpMux来使用 自己想要的middleware？

**Comment by defool** [comment]
可以用，下面是个例子：
```
package main

import (
	"fmt"
	"net/http"

	"github.com/TarsCloud/TarsGo/tars"
	"github.com/gorilla/mux"
)

func main() {
	r := mux.NewRouter()
	r.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		fmt.Fprintf(w, "Home")
	})
	r.HandleFunc("/products/{key}", func(w http.ResponseWriter, r *http.Request) {
		vars := mux.Vars(r)
		w.WriteHeader(http.StatusOK)
		fmt.Fprintf(w, "product: %v\n", vars["key"])
	})

	cfg := tars.GetServerConfig()
	tarsMux := tars.TarsHttpMux{}
	tarsMux.Handle("/", r)
	tars.AddHttpServant(&tarsMux, cfg.App+"."+cfg.Server+".MainObjObj")

	tars.Run()
}
```

**Comment by Clark-zhang** [comment]
好的，感谢 🙏

**Comment by Clark-zhang** [comment]
> 可以用，下面是个例子：
> 
> ```
> package main
> 
> import (
> 	"fmt"
> 	"net/http"
> 
> 	"github.com/TarsCloud/TarsGo/tars"
> 	"github.com/gorilla/mux"
> )
> 
> func main() {
> 	r := mux.NewRouter()
> 	r.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
> 		w.WriteHeader(http.StatusOK)
> 		fmt.Fprintf(w, "Home")
> 	})
> 	r.HandleFunc("/products/{key}", func(w http.ResponseWriter, r *http.Request) {
> 		vars := mux.Vars(r)
> 		w.WriteHeader(http.StatusOK)
> 		fmt.Fprintf(w, "product: %v\n", vars["key"])
> 	})
> 
> 	cfg := tars.GetServerConfig()
> 	tarsMux := tars.TarsHttpMux{}
> 	tarsMux.Handle("/", r)
> 	tars.AddHttpServant(&tarsMux, cfg.App+"."+cfg.Server+".MainObjObj")
> 
> 	tars.Run()
> }
> ```
好的，感谢 🙏

**Comment by Clark-zhang** [comment]
Hi, @defool @sandyskies 

这种方式虽然可以使用中间件，但是目前tars监控上，所有的客户端接口，都变成了 /。
可能是因为tarsHttp里只注册了一个 / 导致的？

能帮忙看下吗？

**Comment by Clark-zhang** [comment]
> Hi, @defool @sandyskies
> 
> 这种方式虽然可以使用中间件，但是目前tars监控上，所有的 “接口名”，都变成了 /。
> 可能是因为tarsHttp里只注册了一个 / 导致的？
> 
> 能帮忙看下吗？

可以把注册在gorilla上的 route，再多注册一次到 TarsHtppMux上就可以部分解决该问题。
