### ISSUE TITLE
windows 安装 tars

### ISSUE THREAD

**Issue by lizihuai** [TarsCloud/TarsGo#141]
目前tars没有支持windows安装和运行吗?如果支持的话,麻烦给下安装教程

**Comment by KatharineOzil** [comment]
![image](https://user-images.githubusercontent.com/13435037/65401425-9c93b880-ddfa-11e9-892b-fe804ee1625f.png)
https://github.com/TarsCloud/Tars README这边说：TARS只支持在Linux操作系统上部署
