### ISSUE TITLE
如何发送jce请求，可以提供示例

### ISSUE THREAD

**Issue by HyperLiar** [TarsCloud/TarsGo#142]
如题，已经生成go版本的jce序列化文件，如何发送jce请求呢？km,github都找不到例子，麻烦尽快完善下

**Comment by ETZhangSX** [comment]
相关例子km是有的，有关jce的问题最好到内网问。

关于如何调用使用tars协议服务的接口，可以在[TarsGo文档客户端开发](https://github.com/TarsCloud/TarsGo/blob/master/docs/tars_go_quickstart.md#客户端开发)部分查看相关用法。

相关例子可以参考[TarsGo/examples/EchoClientServer/EchoClientServer.go](https://github.com/TarsCloud/TarsGo/blob/master/examples/EchoClientServer/EchoClientServer.go)，包含了在一个服务中如何调用其它tars协议服务的完整过程

先创建一个全局的`*tars.Communicator`通信器对象
>https://github.com/TarsCloud/TarsGo/blob/2c6dd1e2f41ac0d0cd228846bdd84c8d1e8a6066/examples/EchoClientServer/EchoClientServer.go#L17

在需要调用其它服务的时候，新建该服务的proxy对象，该例子中命名为`app`，同时使用通信器对象函数`stringToProxy`初始化proxy对象，参数还需要传入调用的服务名。初始化完成后即可通过proxy对象调用对应服务的接口
>https://github.com/TarsCloud/TarsGo/blob/2c6dd1e2f41ac0d0cd228846bdd84c8d1e8a6066/examples/EchoClientServer/EchoClientServer.go#L35-L38

希望以上信息对你有帮助
