### ISSUE TITLE
tarsgo  set模式开启问题

### ISSUE THREAD

**Issue by davidxiaozhi** [TarsCloud/TarsGo#143]
基于 targo web 配置好 服务实例Set后,基于模板生成的配置是小写,但是 application 代码当中判断的字符是大写

![4B74AF74181CEA6698DD3C0ABD830E91](https://user-images.githubusercontent.com/6194818/64099711-84e98700-cd9c-11e9-881a-71d2967d5d6f.jpg)

![1529C44E5B130A3A1B8D8086BA59FCFD](https://user-images.githubusercontent.com/6194818/64099714-85821d80-cd9c-11e9-9940-147dccf24fdc.jpg)

**Comment by davidxiaozhi** [comment]
自动生成的配置文件中 enableset=y
<tars>
        <application>
                enableset=y
                setdivision=a.a.1
                <server>
                        node=tars.tarsnode.ServerObj@tcp -h 172.17.0.4 -p 19386 -t 60000
                        app=amc
                        server=GoWebServer
                        localip=172.17.0.4
                        local=tcp -h 127.0.0.1 -p 20020 -t 3000
                        basepath=/usr/local/app/tars/tarsnode/data/amc.GoWebServer/bin/
                        datapath=/usr/local/app/tars/tarsnode/data/amc.GoWebServer/data/
                        logpath=/usr/local/app/tars/app_log/
                        logsize=10M
                        config=tars.tarsconfig.ConfigObj
                        notify=tars.tarsnotify.NotifyObj
                        log=tars.tarslog.LogObj
                        deactivating-timeout=3000
                        logLevel=DEBUG
                        <amc.GoWebServer.GoWebObjAdapter>
                                allow
                                endpoint=tcp -h 172.17.0.4 -p 20020 -t 60000
                                handlegroup=amc.GoWebServer.GoWebObjAdapter
                                maxconns=200000
                                protocol=not_tars
                                queuecap=10000
                                queuetimeout=60000
                                servant=amc.GoWebServer.GoWebObj
                                threads=5
                        </amc.GoWebServer.GoWebObjAdapter>
                </server>
                <client>
                        locator=tars.tarsregistry.QueryObj@tcp -h 172.17.0.3 -p 17890
                        sync-invoke-timeout=3000
                        async-invoke-timeout=5000
                        refresh-endpoint-interval=60000
                        stat=tars.tarsstat.StatObj
                        property=tars.tarsproperty.PropertyObj
                        report-interval=60000
                        sample-rate=100000
                        max-sample-count=50
                        asyncthread=3
                        modulename=amc.GoWebServer
                </client>
        </application>
</tars>

而 application.go 当中65 行判断该配置 为大写字符 Y
`
if c.GetString("/tars/application<enableset>") == "Y" {
		svrCfg.Enableset = true
		svrCfg.Setdivision = c.GetString("/tars/application<setdivision>")
	}
`

**Comment by chenhengqi** [comment]
see https://github.com/TarsCloud/TarsGo/pull/134
