### ISSUE TITLE
invalid memory address or nil pointer dereference error in statf

### ISSUE THREAD

**Issue by XuefengHuang** [TarsCloud/TarsGo#147]
```
//StatReport is global.
var StatReport *StatFHelper
```
这个StatReport没有对里面的mutex和list实例化就直接引用，导致```pushBackMsg```函数里面相关地方panic,报错信息：```invalid memory address or nil pointer dereference```

**Comment by ETZhangSX** [comment]
mutex和list是有实例化的，在`StatFHelper`中的`Init`中定义了
>https://github.com/TarsCloud/TarsGo/blob/2c6dd1e2f41ac0d0cd228846bdd84c8d1e8a6066/tars/statf.go#L33-L43

并在`initReport`中进行了实例化`StatReport`对象，只有`GetClientConfig`返回`nil`时，不会进行实例化
>https://github.com/TarsCloud/TarsGo/blob/2c6dd1e2f41ac0d0cd228846bdd84c8d1e8a6066/tars/statf.go#L124-L135

同时在服务启动时调用`initReport`来初始化`StatReport`对象
>https://github.com/TarsCloud/TarsGo/blob/2c6dd1e2f41ac0d0cd228846bdd84c8d1e8a6066/tars/application.go#L155

所以你的pr中添加的修改和源码中的重复了。没有实例化成功是`GetClientConfig`返回nil，可以排查一下这方面的原因。

希望以上信息对你有帮助。如果问题已经解决，请关闭相关issue和pr；若有新的问题，可以开启新的issue

**Comment by XuefengHuang** [comment]
非常感谢你的解答！
