### ISSUE TITLE
make 脚本建议支持交叉编译参数

### ISSUE THREAD

**Issue by bobzhangyong** [TarsCloud/TarsGo#151]
目前的make 脚本没有支持交叉编译，我再mac上面编译的二进制文件无法在linux上执行。

执行如下代码 可以设置交叉编译

CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build

建议将这个配置参数化 放到项目的makefile中

**Comment by defool** [comment]
需要交叉编译时可以在make命令加上参数, 比如`make GOOS=linux`, 不建议过多配置.
