### ISSUE TITLE
pb2tarsgo tool:  missing main function

### ISSUE THREAD

**Issue by tensorchen** [TarsCloud/TarsGo#162]
```bash
$ go build ./...

# github.com/TarsCloud/TarsGo/tars/tools/pb2tarsgo/protoc-gen-go
runtime.main_main·f: function main is undeclared in the main package
```

**Comment by defool** [comment]
[https://github.com/TarsCloud/TarsGo/blob/master/tars/tools/pb2tarsgo/README.md](https://github.com/TarsCloud/TarsGo/blob/master/tars/tools/pb2tarsgo/README.md)

Please build the tool according this guide.
