### ISSUE TITLE
Is there a performance checking tool like pprof available?

### ISSUE THREAD

**Issue by TomatoMr** [TarsCloud/TarsGo#169]

**Comment by Formergg** [comment]
![image](https://user-images.githubusercontent.com/7497817/79038908-c9c97c00-7c0f-11ea-85d7-273440e86799.png)
Maybe you can use pprof in tars manager panel.
**Step:**
Services - Operates more - send customer cmd  -  input "tars.pprof"
**Reference Code:**
https://github.com/TarsCloud/TarsGo/blob/master/tars/admin.go#L76
Then you can open "http://your node ip:8080/debug/pprof" to deal with it.
**Generate svg file:**
`go tool pprof -svg http://your node ip:8080/debug/pprof/profile?seconds=10`

Hope it helps you

**Comment by TomatoMr** [comment]
:)Thank you. That's exactly what I want.



---Original---
