### ISSUE TITLE
请问哪个函数可以实现往`服务管理>服务实时状态`(图中箭头指的地方)发消息，然后在tars的前端显示出来呢？

### ISSUE THREAD

**Issue by TARS-Robot-Question** [TarsCloud/TarsGo#182]
![WechatIMG21a91a3b2a237258fae884062f994355](https://user-images.githubusercontent.com/62690574/77629979-51af5500-6f85-11ea-8f15-74c1651e0cb9.jpeg)

**Comment by TARS-Robot-Answer** [comment]
首先要从模版配置里面获得 `tars/application/server - notify - tars.tarsnotify.NotifyObj`的值，假设叫做 `notify`
```go
ha := &tars.NotifyHelper{}
comm := tars.NewCommunicator()
conf := tars.GetServerConfig()
ha.SetNotifyInfo(comm, notify, conf.App, conf.Server, conf.Container)
ha.ReportNotifyInfo("Hello, world")
```

或者默认的 `notify` 没改的话，直接 `notify := "tars.tarsnotify.NotifyObj"` 也可以
