### ISSUE TITLE
Make NewServantProxy public to enable user to develop custom gateway server for tars services

### ISSUE THREAD

**Issue by jarod** [TarsCloud/TarsGo#206]
tars/servant.go:
```go
func NewServantProxy(comm *Communicator, objName string) *ServantProxy {
	return newServantProxy(comm, objName)
}
```

**Comment by defool** [comment]
Tars provides the gateway server: https://github.com/TarsCloud/TarsGateway, why do you want to develop custom gateway?

**Comment by jarod** [comment]
> Tars provides the gateway server: https://github.com/TarsCloud/TarsGateway, why do you want to develop custom gateway?
自己实现网关可以实现除了http以外的其他传输接入方式，比如TCP socket, websocket
而且，发这个issue的时候TarsGateway还不存在
