### ISSUE TITLE
atomic 组合之后不再是一个原子操作 

### ISSUE THREAD

**Issue by iAmYeWeiLong** [TarsCloud/TarsGo#211]
期望 op1,op2,op1,op2,op1,op2.... 但有可能是 op1,op1,op1,op2,op2,op2 .
88 行检查 msgID 是否刚好等于 maxInt32，若相等则置为 1。假设 msgID 值为 maxInt32-1 时,有多个执行流分别经过时都不会置为 1，后面的 105 行再多次进行 add 就可能产生负数的 msgID (有符号整数溢出回转为负数)，自此之后长时间内都是负数的 id

![atomic](https://user-images.githubusercontent.com/36838496/84878415-626ef300-b0bc-11ea-8a3d-9b71b8365b78.png)

**Comment by maplebeats** [comment]
这个在很久以前就评审过了，主要看的是这个值是用来干什么的，requestid只是用来标记请求的，只要能保证队列中的请求唯一性就好，并不需要强一致，想达到绝对的防止溢出会损失掉不必要的性能，当然你有更好的方案可以提一下pr:D

**Comment by iAmYeWeiLong** [comment]
明白。允许负数的话，就只需避免为 0 就行了，看了代码，RequestID 值为 0 专用于 server 推送消息给 client ，让 client 主动 close()。

https://github.com/TarsCloud/TarsGo/pull/212

**Comment by iAmYeWeiLong** [comment]
如果真不想有负数出现，就只能改成 uint32 了，但这样估计改动大，也有点吹毛求疵了。估计 RequestID 设计为有符号的是因为 java 没有无符号整数吧
