### ISSUE TITLE
关于主控服务 Registry 的健康检查问题

### ISSUE THREAD

**Issue by ye-wei-long** [TarsCloud/TarsGo#214]
直接寻址模式的都没有健康检查，但是主控服务 Registry 也是直接寻址的，可能是个 bug.
![微信图片_20200623164759](https://user-images.githubusercontent.com/36838496/85382333-7067bc80-b571-11ea-8674-67bc251bcf86.png)

**Comment by defool** [comment]
直接寻址模式下，是在调用失败后才会触发熔断。
除了调用主控服务，其他服务一般都不是直接寻址的，而主控服务本身有降级，所以这里不太有必要去优化
