### ISSUE TITLE
build error when return bool in tars interface file

### ISSUE THREAD

**Issue by Hotwill** [TarsCloud/TarsGo#217]
in .tars file, if I define a function that return bool, like this:
```
interface TestService{
    bool process(string cmd);
};
```

The go source code generates by tars2go can't build successfully. The error is:
```
cannot use _funRet_ (type bool) as type int32 in argument to _os.Write_int32
```

**Comment by defool** [comment]
I can't reproduce the problem, can you check again and provide the version of `tars2go`?
