### ISSUE TITLE
There are some Chinese characters in the command "tars2go -h"

### ISSUE THREAD

**Issue by wnote** [TarsCloud/TarsGo#22]
Below is the output of the command "tars2go -h" :
`Usage: tars2go [flags] *.tars
       tars2go -I tars/protocol/res/endpoint [-I ...] QueryF.tars
  -E    生成未fmt前的代码便于排错
  -I value
        指定具体的import路径
  -add-servant
        生成AddServant函数 (default true)
  -outdir string
        生成的代码放到哪个目录
  -tarsPath string
        specify the tars source path. (default "github.com/TarsCloud/TarsGo/tars")`

**Comment by sandyskies** [comment]
Thanks for reporting,  I will fixed this later!

**Comment by sandyskies** [comment]
https://github.com/TarsCloud/TarsGo/commit/07c5666280c17ec4f80a6d09747510f4303a1169
