### ISSUE TITLE
tars2go 1.1.4 对于返回值非int或者void的生成代码默认Write_int32

### ISSUE THREAD

**Issue by dpp2009** [TarsCloud/TarsGo#222]
比如   vector< EndpointF > findObjectById(string id);
编译报错   cannot use _funRet_ (type []EndpointF) as type int32 in argument to _os.Write_int32

需要将
    err = _os.Write_int32(_funRet_, 0)
改成
     err = _os.WriteHead(codec.LIST, 0)

           if tarsReq.IVersion == basef.TARSVERSION {
			_os.Reset()

			//bug !!!
			//err = _os.Write_int32(_funRet_, 0)
			err = _os.WriteHead(codec.LIST, 0)
			if err != nil {
				return err
			}

		} else if tarsReq.IVersion == basef.TUPVERSION {
			_tupRsp_ := tup.NewUniAttribute()

			_os.Reset()

			//bug !!!
			//err = _os.Write_int32(_funRet_, 0)
			err = _os.WriteHead(codec.LIST, 0)
			if err != nil {
				return err
			}
			_tupRsp_.PutBuffer("", _os.ToBytes())
			_tupRsp_.PutBuffer("tars_ret", _os.ToBytes())

			_os.Reset()
			err = _tupRsp_.Encode(_os)
			if err != nil {
				return err
			}
		}

**Comment by YiFabao** [comment]
这样改太复杂了吧，我是这样改的：

`	if fun.HasRet {
		funRetType := gen.genType(fun.RetType)
		c.WriteString(`
		err = _os.Write_`+funRetType+`(_funRet_, 0)
		if err != nil {
			return err
		}		
`)`
