### ISSUE TITLE
请问有没有方便的上传tgz包的工具啊

### ISSUE THREAD

**Issue by lerosua** [TarsCloud/TarsGo#229]
开发阶段，随便改点东西，打包，点上传，点发布，这个步骤很多，浪费时间啊。
没有工具能在客户端直接把tgz包post到web管理端吗？

**Comment by YiFabao** [comment]
可以在本地启动开发调试啊

**Comment by ETZhangSX** [comment]
可以使用`TarsWeb`的API `upload_and_publish` 来上传发布，接口具体信息可以看到 [TarsWeb 的接口文档](https://tarscloud.github.io/TarsDocs/dev/tars-web-api.html#upload-and-publish)，TarsGo的cmake管理的项目中可以直接通过`make`命令上传发布，实际上也是通过Web的API，具体用法可以参考TarsGo的关于[cmake管理项目的文档](https://tarscloud.github.io/TarsDocs/dev/tarsgo/spec.html)

**Comment by ruanshudong** [comment]
https://doc.tarsyun.com/adminer/start/index.html#/tarsdoc/dev/tarsgo/spec.md
其实可以用cmake来管理代码, 可以直接make upload来上传
