### ISSUE TITLE
TarsGo客户端不会自动上报stat和property

### ISSUE THREAD

**Issue by Joncer** [TarsCloud/TarsGo#231]
TarsGo客户端，如果不是部署在Tars框架内的话，不会自动上报state和property。而TarsJava即使不部署在Tars框架内，也会正常自动上报，这个特性还是很好用的，用到的场景也比较多，因为很多情况下，服务是不会部署在Tars框架内的。
使用的是当前最新的TarsGo release版本1.1.4，不知道有没有计划解决这一问题。

**Comment by defool** [comment]
确实有必要实现，是否有愿意提供方案或直接提PR？

**Comment by lbbniu** [comment]
> 确实有必要实现，是否有愿意提供方案或直接提PR？

我准备提pr，怎么成功 contributors

**Comment by defool** [comment]
看了提交的方案，感觉对原application.go做了比较多侵入性的改造，会原有功能稳定性有潜在的影响，建议调整一下：
最终只需要调整statf.go和property.go即可，以statf为例，可以增加一个类似`StatConfig`的结构体，将依赖的clientconfig/serverconfig字段放到里面，另外加一个类似`InitForClientMode`函数入口，传入上报功能依赖的`Communitor`和`StatConfig`。

**Comment by lbbniu** [comment]
> 果不是部署在Tars框架内的话，不会自动上报state和property。而TarsJava即使不部署在Tars框架内，也会正常自动上报，这个特性还是很好用的，用到的场景也比较多，因为很多情况下，服务是不会部署在Tars框架内的。
> 使用的是当前最新的TarsGo release版本1.1.4，不知道有没

对标了java的实现，让使用起来更透明化

**Comment by lbbniu** [comment]
> 看了提交的方案，感觉对原application.go做了比较多侵入性的改造，会原有功能稳定性有潜在的影响，建议调整一下： 最终只需要调整statf.go和property.go即可，以statf为例，可以增加一个类似`StatConfig`的结构体，将依赖的clientconfig/serverconfig字段放到里面，另外加一个类似`InitForClientMode`函数入口，传入上报功能依赖的`Communitor`和`StatConfig`。

对标了java的实现，让使用起来更透明化

**Comment by lbbniu** [comment]
v1.1.8 开始支持自动上报
