### ISSUE TITLE
unknown plugin "tarsrpc"

### ISSUE THREAD

**Issue by edward-golang** [TarsCloud/TarsGo#260]
我按照pb2tarsgo的教程使用时，报下面的错误，请问怎么处理？
[root@localhost proto]# protoc --go_out=plugins=tarsrpc:. helloworld.proto
WARNING: Package "github.com/golang/protobuf/protoc-gen-go/generator" is deprecated.
        A future release of golang/protobuf will delete this package,
        which has long been excluded from the compatibility promise.

2020/11/24 21:38:40 WARNING: Missing 'go_package' option in "helloworld.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

--go_out: protoc-gen-go: unknown plugin "tarsrpc"

**Comment by tesion99** [comment]
See http://shangdixinxi.com/detail-1428690.html to solve this problem

**Comment by langxgm** [comment]
use github.com/golang/protobuf v1.3.5
