### ISSUE TITLE
接口处理groutine panic进程直接退出

### ISSUE THREAD

**Issue by MeiJunh** [TarsCloud/TarsGo#271]
发现接口函数没有开启新groutine，panic后也会导致整个进程的panic。
   查看框架内部实际上在invoke的时候是有调用CheckPanic的，

https://github.com/TarsCloud/TarsGo/blob/26a06ecd0a2b89b084f33c51560ce296e8c6206d/tars/tarsprotocol.go#L36

但是这个CheckPanic函数会直接exit，没有达到recover的效果，和请求分发在同一个groutine的panic是否也需要业务方自己recover，例如在filter中进行recover

**Comment by defool** [comment]
https://github.com/TarsCloud/TarsGo/blob/26a06ecd0a2b89b084f33c51560ce296e8c6206d/tars/panic.go#L21
这2行可以去掉，考虑可能出现大量panic，可以在生成panic文件加个频控。

@MeiJunh 方便提个MR？

**Comment by MeiJunh** [comment]
> https://github.com/TarsCloud/TarsGo/blob/26a06ecd0a2b89b084f33c51560ce296e8c6206d/tars/panic.go#L21
> 
> 
> 这2行可以去掉，考虑可能出现大量panic，可以在生成panic文件加个频控。
> @MeiJunh 方便提个MR？

这个频控监测是加到内存里么？感觉仅仅是监测日志记录其实不太能及时的获取到panic信息，进程直接down掉对业务影响又比较大，目前我们这边在使用的时候是遇到panic后进行告警信息通知发送。
 
 看是直接去掉
 rogger.FlushLogger() 
os.Exit(-1)
这两行提一个mr，还是需要加上以函数文件为指标的panic频率监控再提一个mr？

**Comment by defool** [comment]
> > https://github.com/TarsCloud/TarsGo/blob/26a06ecd0a2b89b084f33c51560ce296e8c6206d/tars/panic.go#L21
> > 
> > 这2行可以去掉，考虑可能出现大量panic，可以在生成panic文件加个频控。
> > @MeiJunh 方便提个MR？
> 
> 这个频控监测是加到内存里么？感觉仅仅是监测日志记录其实不太能及时的获取到panic信息，进程直接down掉对业务影响又比较大，目前我们这边在使用的时候是遇到panic后进行告警信息通知发送。
> 
> 看是直接去掉
> rogger.FlushLogger()
> os.Exit(-1)
> 这两行提一个mr，还是需要加上以函数文件为指标的panic频率监控再提一个mr？

加一个OnPanic的回调感觉比较合理，默认回调是把panic信息打到本地文件，频控可以用golang.org/x/time/rate，没有频控可以评估下，可能问题也不大。

**Comment by MeiJunh** [comment]
> > > https://github.com/TarsCloud/TarsGo/blob/26a06ecd0a2b89b084f33c51560ce296e8c6206d/tars/panic.go#L21
> > > 
> > > 这2行可以去掉，考虑可能出现大量panic，可以在生成panic文件加个频控。
> > > @MeiJunh 方便提个MR？
> > 
> > 
> > 这个频控监测是加到内存里么？感觉仅仅是监测日志记录其实不太能及时的获取到panic信息，进程直接down掉对业务影响又比较大，目前我们这边在使用的时候是遇到panic后进行告警信息通知发送。
> > 看是直接去掉
> > rogger.FlushLogger()
> > os.Exit(-1)
> > 这两行提一个mr，还是需要加上以函数文件为指标的panic频率监控再提一个mr？
> 
> 加一个OnPanic的回调感觉比较合理，默认回调是把panic信息打到本地文件，频控可以用golang.org/x/time/rate，没有频控可以评估下，可能问题也不大。

回调函数可以直接加上去，针对panic所在文件的频控添当达到频控次数后是进行日志刷盘以及os.exit么？

另外我尝试了一下好像没有推送代码的权限。

**Comment by ETZhangSX** [comment]
> > > > https://github.com/TarsCloud/TarsGo/blob/26a06ecd0a2b89b084f33c51560ce296e8c6206d/tars/panic.go#L21
> > > > 
> > > > 这2行可以去掉，考虑可能出现大量panic，可以在生成panic文件加个频控。
> > > > @MeiJunh 方便提个MR？
> > > 
> > > 
> > > 这个频控监测是加到内存里么？感觉仅仅是监测日志记录其实不太能及时的获取到panic信息，进程直接down掉对业务影响又比较大，目前我们这边在使用的时候是遇到panic后进行告警信息通知发送。
> > > 看是直接去掉
> > > rogger.FlushLogger()
> > > os.Exit(-1)
> > > 这两行提一个mr，还是需要加上以函数文件为指标的panic频率监控再提一个mr？
> > 
> > 
> > 加一个OnPanic的回调感觉比较合理，默认回调是把panic信息打到本地文件，频控可以用golang.org/x/time/rate，没有频控可以评估下，可能问题也不大。
> 
> 回调函数可以直接加上去，针对panic所在文件的频控添当达到频控次数后是进行日志刷盘以及os.exit么？
> 
> 另外我尝试了一下好像没有推送代码的权限。

应该是说 PR

Fork 后修改，然后创建一个 PR 即可

**Comment by MeiJunh** [comment]
> > > > > https://github.com/TarsCloud/TarsGo/blob/26a06ecd0a2b89b084f33c51560ce296e8c6206d/tars/panic.go#L21
> > > > > 
> > > > > 这2行可以去掉，考虑可能出现大量panic，可以在生成panic文件加个频控。
> > > > > @MeiJunh 方便提个MR？
> > > > 
> > > > 
> > > > 这个频控监测是加到内存里么？感觉仅仅是监测日志记录其实不太能及时的获取到panic信息，进程直接down掉对业务影响又比较大，目前我们这边在使用的时候是遇到panic后进行告警信息通知发送。
> > > > 看是直接去掉
> > > > rogger.FlushLogger()
> > > > os.Exit(-1)
> > > > 这两行提一个mr，还是需要加上以函数文件为指标的panic频率监控再提一个mr？
> > > 
> > > 
> > > 加一个OnPanic的回调感觉比较合理，默认回调是把panic信息打到本地文件，频控可以用golang.org/x/time/rate，没有频控可以评估下，可能问题也不大。
> > 
> > 
> > 回调函数可以直接加上去，针对panic所在文件的频控添当达到频控次数后是进行日志刷盘以及os.exit么？
> > 另外我尝试了一下好像没有推送代码的权限。
> 
> 应该是说 PR
> 
> Fork 后修改，然后创建一个 PR 即可

谢谢，已经提了pr，https://github.com/TarsCloud/TarsGo/pull/278，看是否满足要求，只加了一个onPanic回调函数，没有对panic进行频控。
