### ISSUE TITLE
服务优雅退出时没有先关闭注册中心心跳

### ISSUE THREAD

**Issue by MeiJunh** [TarsCloud/TarsGo#279]
https://github.com/TarsCloud/TarsGo/blob/4ba232594bb32b3ae3be77d8892a36d7bfc13194/tars/application.go#L439

graceShutdown函数在进程退出时，将listen端口关闭，然后处理退出信号前的请求，最后才去停止心跳。导致服务升级时，如果请求量过大时，在优雅退出的一段时间内，注册中心仍然认为该退出进程存活。会使得其他服务进程继续请求正在退出的进程然后返回超时错误。

是否将teerDown停止keepalive心跳函数放在listen端口关闭之后会比较合理，这样在注册中心就不会认为这个进程还存活。

**Comment by chenhengqi** [comment]
新的请求应该会到新的进程

**Comment by MeiJunh** [comment]
> 新的请求应该会到新的进程

注册中心认为它是存活的，新请求应该还是会到这个要退出的进程吧。 
因为现在我们在进行服务升级的时候发现会出现超时请求服务。排查问题应该是这里导致的，退出进程实际没有提供服务，但是客户端和注册中心认为他是存活的，所以继续发送请求然后请求超时。

**Comment by chenhengqi** [comment]
是什么协议的服务？优雅退出时间是多少？

**Comment by MeiJunh** [comment]
> 是什么协议的服务？优雅退出时间是多少？

使用的是pb协议，优雅退出时间是默认的60000ms

**Comment by defool** [comment]
graceShutdown主要是解决服务优雅重启的问题，优雅退出应该要另外方案，@MeiJunh 这里是否相关想法或方案？

**Comment by defool** [comment]
如无相关回复就先关闭，有需要可以重新打开
