### ISSUE TITLE
"github.com/openzipkin-contrib/zipkin-go-opentracing"  v0.3.5 版本报错

### ISSUE THREAD

**Issue by SmileFisher** [TarsCloud/TarsGo#290]
tars/plugin/zipkintracing/zipkintracing.go  43行
建议升级到v0.4.5

**Comment by chenhengqi** [comment]
This could be closed once #275  get merged.

**Comment by SmileFisher** [comment]
TKS

**Comment by defool** [comment]
Fixed in https://github.com/TarsCloud/TarsGo/pull/320
