### ISSUE TITLE
go 1.16版本 $GOPATH下并没有src目录，故而无视使用 tools 下的生成服务模版的脚本

### ISSUE THREAD

**Issue by aiyogg** [TarsCloud/TarsGo#291]
请问无有优雅的方法继续按文档方式使用tools下的脚本新建服务模版和使用cmake打包

**Comment by defool** [comment]
默认的服务模板应该要升级到go mod了，然后不用关心GOPATH的问题。 @aiyogg 是否有意愿提个PR?

**Comment by aiyogg** [comment]
> 默认的服务模板应该要升级到go mod了，然后不用关心GOPATH的问题。 @aiyogg 是否有意愿提个PR?
我理解的是需要用go翻译下那几个shell脚本，将初始化服务模板能单独作为 module 来install? 工作节奏缓和下来了我可以试试

**Comment by defool** [comment]
> > 默认的服务模板应该要升级到go mod了，然后不用关心GOPATH的问题。 @aiyogg 是否有意愿提个PR?
> 
> 我理解的是需要用go翻译下那几个shell脚本，将初始化服务模板能单独作为 module 来install? 工作节奏缓和下来了我可以试试

是的，欢迎提PR.

**Comment by defool** [comment]
@aiyogg 这里有进展吗？

**Comment by aiyogg** [comment]
> @aiyogg 这里有进展吗？

目前没有进展-_-!

**Comment by defool** [comment]
先关闭，有必要再重新打开
