### ISSUE TITLE
Wrong index in endpoint manager

### ISSUE THREAD

**Issue by BaBahsq** [TarsCloud/TarsGo#292]
endpointmanager.go
	
	sort.Slice(sortedEps, func(i int, j int) bool {
	--	return crc32.ChecksumIEEE([]byte(sortedEps[i].Key)) < crc32.ChecksumIEEE([]byte(sortedEps[i].Key))
	++   return crc32.ChecksumIEEE([]byte(sortedEps[i].Key)) < crc32.ChecksumIEEE([]byte(sortedEps[j].Key))
	})

**Comment by defool** [comment]
Would you like to submit a fix?

**Comment by defool** [comment]
#293
