### ISSUE TITLE
嵌套 MsgOutGameShowF3 byte [3]  这样生成go 文件有错

### ISSUE THREAD

**Issue by xjaksyt2008** [TarsCloud/TarsGo#297]
struct MsgOutGameShowF3{
	 1 require byte count[3];
};

struct MsgOutGameShowF64{
	 1 require byte count[64];
};

struct MsgOutGameShowF20{
	 1 require byte count[20];
};

struct DMsgOutGameShow{
	10 require MsgOutGameShowF3	fff[5];	
	12 require MsgOutGameShowF64   ffgf[5];	
};

**Comment by defool** [comment]
是需要定义数组吗？可以用vector

**Comment by xjaksyt2008** [comment]
另外一个端使用的c++, 用vector 有点问题

**Comment by xjaksyt2008** [comment]
是定义的二维数组
