### ISSUE TITLE
gtime data race

### ISSUE THREAD

**Issue by chaoanweng** [TarsCloud/TarsGo#299]
WARNING: DATA RACE
Read at 0x0000017d1240 by goroutine 25:
  vrGo/pkg/tarsGo/tars.(*globalManager).updateEndpoints()
    tars/endpointmanager.go:140 +0x71c

Previous write at 0x0000017d1240 by goroutine 7:
  vrGo/pkg/tarsGo/tars/util/gtime.init.0.func1()
     tars/util/gtime/gtime.go:28 +0x1a8
项目启动的时候和没隔一段时间会有这个报错。

**Comment by defool** [comment]
这个是tars提供了一种性能更高的获取时间方式（精确到秒），不影响使用
