### ISSUE TITLE
请问关于性能测试可以提供详细的测试脚本吗?

### ISSUE THREAD

**Issue by myonlyzzy** [TarsCloud/TarsGo#30]
请问关于性能测试可以提供详细的测试脚本吗?我测试的结果和你们提供的数据有很大出入,关于grpc请问你们性能测试的时候使用了什么生成插件,gogofast or 原生的插件？

**Comment by sandyskies** [comment]
1，  建议setting.go ： var MaxInvoke int = runtime.NumCpu()
另外，communicator 只new一次，不要多次new communicator ，测试脚本长驻，多个协程并发发起请求，
2， 使用了原生的插件
