### ISSUE TITLE
tars-go与client交互协议

### ISSUE THREAD

**Issue by liulinghao0421** [TarsCloud/TarsGo#306]
请问现在tars-go版本已经支持not_tars协议交互吗？看了源码似乎目前只支持tars协议交互，没有看到相关not_tars协议实现源码，谢谢！！！

**Comment by defool** [comment]
一般使用not_tars协议（如http）的客户端都有现成的，不需要tars-go还实现。
这里有什么场景需要tars-go来做呢？

**Comment by liulinghao0421** [comment]
你好，有想法用tars-go来做游戏开发，跟客户端c#交互，需要用tcp来做，所以这边参考了tars-c++版本是有基于not_tars协议来进行交互处理协议的，目前是不支持呢？

**Comment by defool** [comment]
服务端有支持自定义协议，可以参考这里：https://github.com/TarsCloud/TarsGo/blob/master/_examples/CustomProtoServer/CustomProtoServer.go#L10
