### ISSUE TITLE
怎么自定义负载均衡

### ISSUE THREAD

**Issue by manchurio** [TarsCloud/TarsGo#310]
有什么方法可以自定义负载均衡，
比如我想优先调用 最新patch version 的servant，要怎么做

**Comment by defool** [comment]
从registry获取的节点信息中没有patch版本信息，目前看这个功能实现成本比较高

**Comment by manchurio** [comment]
@defool 不拿patch version也行， 是否可以自定义数据给servant， client可以拿到这些自定义数据，然后client 再自定义负载均衡

**Comment by defool** [comment]
> servant

目前看没有可以自定义的数据，比较认可支持每个节点有自定义元数据，不过需要比较大的改动，涉及到tarsregistry/tarsweb/各语言sdk支持

**Comment by baiweiguo** [comment]
您好！您的邮件已收到，我将会尽快地进行处理，谢谢来信！
