### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by tangj1992** [TarsCloud/TarsGo#315]
存在makefile，但是make找不到，-f指定也不行
![1641115222(1)](https://user-images.githubusercontent.com/13653933/147871566-2f246dba-6ab8-4011-b94a-33a541989322.png)

**Comment by lbbniu** [comment]
> 存在makefile，但是make找不到，-f指定也不行 ![1641115222(1)](https://user-images.githubusercontent.com/13653933/147871566-2f246dba-6ab8-4011-b94a-33a541989322.png)

是不是makefile的格式有问题

**Comment by defool** [comment]
原因应该是没有把TarsGO clone到$GOPATH/src/github.com目录。

另外可以考虑切换到go.mod方案，参考#311

**Comment by tangj1992** [comment]
我直接用go build编译，然后自己打包程tgz文件，可以正常发布了
