### ISSUE TITLE
有个服务跑着跑着就挂了，日志也没记录原因

### ISSUE THREAD

**Issue by tangj1992** [TarsCloud/TarsGo#318]
![0c8471b95de069f84541e6c4d119f02](https://user-images.githubusercontent.com/13653933/148646067-f0e6c44b-9d8b-475e-8e66-22e8344b215b.png)

请问这是为什么

**Comment by defool** [comment]
收到这些信号会执行grace shutdown: syscall.SIGUSR2, syscall.SIGKILL, syscall.SIGTERM
确认下是否有外部触发了这些信号？
