### ISSUE TITLE
新版本接口返回void生成代码存在语法错误

### ISSUE THREAD

**Issue by fuyunbo** [TarsCloud/TarsGo#340]

**Comment by lbbniu** [comment]
有相关的demo tars协议文件吗

**Comment by fuyunbo** [comment]
module foamclientadmin
{
	struct Client {
		0 require int id; // 注册成功返回客户端id
	};
	interface FoamClientAdmin
	{
		void KeepAlive(Client client);
	};
};

**Comment by fuyunbo** [comment]
//KeepAliveWithContext is the proxy function for the method defined in the tars file, with the context
func (_obj *FoamClientAdmin) KeepAliveWithContext(tarsCtx context.Context, client *Client, _opt ...map[string]string) (err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	_os := codec.NewBuffer()
	err = client.WriteBlock(_os, 1)
	if err != nil {
		return err
	}

	traceData, ok := current.GetTraceData(tarsCtx)
	if ok && traceData.TraceCall {
		traceData.NewSpan()
		var traceParam string
		traceParamFlag := traceData.NeedTraceParam(trace.EstCS, uint(_os.Len()))
		if traceParamFlag == trace.EnpNormal {
			value := map[string]interface{}{}
			value["client"] = client
			p, _ := json.Marshal(value)
			traceParam = string(p)
		} else if traceParamFlag == trace.EnpOverMaxLen {
			traceParam = "{\"trace_param_over_max_len\":true}"
		}
		tars.Trace(traceData.GetTraceKey(trace.EstCS), trace.TraceAnnotationCS, tars.GetClientConfig().ModuleName, _obj.s.Name(), "KeepAlive", 0, traceParam, "")
	}

	var _status map[string]string
	var _context map[string]string
	if len(_opt) == 1 {
		_context = _opt[0]
	} else if len(_opt) == 2 {
		_context = _opt[0]
		_status = _opt[1]
	}
	_resp := new(requestf.ResponsePacket)

	err = _obj.s.Tars_invoke(tarsCtx, 0, "KeepAlive", _os.ToBytes(), _status, _context, _resp)
	if err != nil {
		return err
	}

	if ok && traceData.TraceCall {
		var traceParam string
		traceParamFlag := traceData.NeedTraceParam(trace.EstCR, uint(_is.Len()))
		if traceParamFlag == trace.EnpNormal {
			value := map[string]interface{}{}
			p, _ := json.Marshal(value)
			traceParam = string(p)
		} else if traceParamFlag == trace.EnpOverMaxLen {
			traceParam = "{\"trace_param_over_max_len\":true}"
		}
		tars.Trace(traceData.GetTraceKey(trace.EstCR), trace.TraceAnnotationCR, tars.GetClientConfig().ModuleName, _obj.s.Name(), "KeepAlive", int(_resp.IRet), traceParam, "")
	}

	if len(_opt) == 1 {
		for k := range _context {
			delete(_context, k)
		}
		for k, v := range _resp.Context {
			_context[k] = v
		}
	} else if len(_opt) == 2 {
		for k := range _context {
			delete(_context, k)
		}
		for k, v := range _resp.Context {
			_context[k] = v
		}
		for k := range _status {
			delete(_status, k)
		}
		for k, v := range _resp.Status {
			_status[k] = v
		}

	}
	_ = length
	_ = have
	_ = ty
	return nil
}

**Comment by fuyunbo** [comment]
_is没有定义

**Comment by lbbniu** [comment]
已修复

**Comment by lbbniu** [comment]
v1.2.2 版本中修复了， 返回值为void 且 没有out参数，生成trace代码逻辑错误
