### ISSUE TITLE
new version creater has issue

### ISSUE THREAD

**Issue by lyq11** [TarsCloud/TarsGo#346]
[lyq11@localhost TenantUserAuthProcess]$ tarsgo make TestApp HelloGo SayHello github.com/Tars/test
🚀 Creating server TestApp.HelloGo, layout repo is https://github.com/TarsCloud/TarsGo.git, please wait a moment.

当前分支没有跟踪信息。
请指定您要合并哪一个分支。
详见 git-pull(1)。

    git pull <远程> <分支>

如果您想要为此分支创建跟踪信息，您可以执行：

    git branch --set-upstream-to=origin/<分支> master

**Comment by lbbniu** [comment]
支持指定分支，可以看下命名帮助说明
```bash
Create a server make project using the repository template. Example:
tarsgo make TeleSafe PhonenumSogouServer SogouInfo github.com/TeleSafe/PhonenumSogouServer

Usage:
  tarsgo make App Server Servant GoModuleName [flags]

Flags:
  -b, --branch string     repo branch
  -h, --help              help for make
  -r, --repo-url string   layout repo (default "https://github.com/TarsCloud/TarsGo.git")
  -t, --timeout string    time out (default "60s")
```
