### ISSUE TITLE
新版的tars2go不支持相对路径

### ISSUE THREAD

**Issue by manchurio** [TarsCloud/TarsGo#360]
新版的tars2go不支持相对路径, 以前的老版本是支持的

![image](https://user-images.githubusercontent.com/82277001/167860128-f24b7e8f-8702-4ef8-9f87-23aceb14e196.png)

这部分代码被删

**Comment by lbbniu** [comment]
> 新版的tars2go不支持相对路径, 以前的老版本是支持的
> 
> ![image](https://user-images.githubusercontent.com/82277001/167860128-f24b7e8f-8702-4ef8-9f87-23aceb14e196.png)
> 
> 这部分代码被删

是否可以提交pr解决

**Comment by manchurio** [comment]
> > 新版的tars2go不支持相对路径, 以前的老版本是支持的
> > ![image](https://user-images.githubusercontent.com/82277001/167860128-f24b7e8f-8702-4ef8-9f87-23aceb14e196.png)
> > 这部分代码被删
> 
> 是否可以提交pr解决

ok

**Comment by lbbniu** [comment]
新  `tars2go` 支持   `-include` 参数，注意兼容性

**Comment by lbbniu** [comment]
@manchurio 有进展吗？

**Comment by manchurio** [comment]
@lbbniu  PR已经提交, 本地tars文件测试通过
