### ISSUE TITLE
go.mod的go版本是1.13实际上用了go1.16才有的函数

### ISSUE THREAD

**Issue by manchurio** [TarsCloud/TarsGo#361]
代码行[tars/tools/tarsgo/internal/base/templates.go:274](https://github.com/TarsCloud/TarsGo/blob/93cb0ee8edc74cbf9784e7c3fb7c5d7d3827a7bf/tars/tools/tarsgo/internal/base/templates.go#L274)
![image](https://user-images.githubusercontent.com/82277001/168421405-14fc39af-cf4e-4306-921d-c40ca317a413.png)
os.WriteFile 这个函数到go 1.16才支持

**Comment by lbbniu** [comment]
<img width="827" alt="image" src="https://user-images.githubusercontent.com/6211983/168562147-670c1fbd-a3e5-4889-973d-966425a13b46.png">

**Comment by manchurio** [comment]
看到了,
