### ISSUE TITLE
Add  GetDomainLine method in ulit/conf.go

### ISSUE THREAD

**Issue by zhixiongdu027** [TarsCloud/TarsGo#376]
Assume the following sample configuration:

```
<tars>
     <nodes>
        172.6.8.11
        172.6.8.12
        172.6.8.13
     </nodes>
</tars>
```

In c++, via method getDomainLine, we can get the
vector<string> {"172.16.8.11", "172.16.8.12", "172.16.8.13" } value

In go, there is no function corresponding to getDomainLine,
and can't get the target value via GetDomain

@lbbniu

**Comment by lbbniu** [comment]
Received, it will be supported in the next version
