### ISSUE TITLE
优雅重启后进程号不对

### ISSUE THREAD

**Issue by phpcyy** [TarsCloud/TarsGo#378]
TarsGo 提供了发送 `tars.gracerestart` 命令来优雅重启程序的能力，重启后 TarsWeb 上的进程号没有更新。

**Comment by lbbniu** [comment]
点击 `服务列表` 旁边的刷新按钮试试
![image](https://user-images.githubusercontent.com/6211983/179886745-51ad5731-87bf-46c5-8fcc-f0b1f4d7fb47.png)

**Comment by phpcyy** [comment]
我这里点了是没用的
