### ISSUE TITLE
context.Current is unSafe

### ISSUE THREAD

**Issue by vincenty1ung** [TarsCloud/TarsGo#389]
path ：tars/util/current/tarscurrent.go:11
context.Current:
1:当前结构体字段虽然都是不可导出的，但是提供了Set函数，当多个g同时操作set出现panic
2: context.Current使用指针传递没有使用非指针副本传递
3：内部map提供Get直接可以获取map，按照*hmap传递多个g读写map出现panic

<img width="974" alt="image" src="https://user-images.githubusercontent.com/31126332/188396436-6045256a-3cdf-4131-9805-e06487c82ae0.png">

end： 不给犯错的机会

**Comment by lbbniu** [comment]
欢迎提交pr解决

**Comment by lbbniu** [comment]
ctx 为啥不在入口处处理好再给其他协成使用呢

**Comment by vincenty1ung** [comment]
> ctx 为啥不在入口处处理好再给其他协成使用呢

这是用户层面的行为，而是不给用户犯错的机会，框架层面应该杜绝

**Comment by lbbniu** [comment]
> > ctx 为啥不在入口处处理好再给其他协成使用呢
> 
> 这是用户层面的行为，而是不给用户犯错的机会，框架层面应该杜绝

go 的 map 并发读写不也都需要用户或业务实现自己处理吗？
