### ISSUE TITLE
protoc-gen-go-tarsrpc生成的rpc接口，参数和返回值，为何没有设置为结构的指针？

### ISSUE THREAD

**Issue by cosmosir** [TarsCloud/TarsGo#394]
protoc-gen-go-tarsrpc生成的rpc接口，参数和返回值，为何没有设置为结构的指针？

使用值传递proto结构会有以下报错，是否有影响？
 RPCFuncReq lock by value: protobuf/TestService.RPCFuncReq contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutexcopylocks

**Comment by baiweiguo** [comment]
您好！您的邮件已收到，我将会尽快地进行处理，谢谢来信！

**Comment by lbbniu** [comment]
> protoc-gen-go-tarsrpc生成的rpc接口，参数和返回值，为何没有设置为结构的指针？
> 
> 使用值传递proto结构会有以下报错，是否有影响？ RPCFuncReq lock by value: protobuf/TestService.RPCFuncReq contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutexcopylocks

为了兼容老的逻辑

**Comment by cosmosir** [comment]
> > protoc-gen-go-tarsrpc生成的rpc接口，参数和返回值，为何没有设置为结构的指针？
> > 使用值传递proto结构会有以下报错，是否有影响？ RPCFuncReq lock by value: protobuf/TestService.RPCFuncReq contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutexcopylocks
> 
> 为了兼容老的逻辑

这个警告可以忽略掉？没啥影响吗？

**Comment by lbbniu** [comment]
需要验证一下
