### ISSUE TITLE
重启服务存在多个进程问题

### ISSUE THREAD

**Issue by snowball1995** [TarsCloud/TarsGo#421]
操作重启出现2个进程问题，版本：3.0.12 
root@kk-1-214:~$ ps -ef | grep userstatus
root      831878       1  7 11:41 ?        00:00:00 /usr/local/app/tars/tarsnode/data/kk.userstatus/bin/userstatus --config=/usr/local/app/tars/tarsnode/data/kk.userstatus/conf/kk.userstatus.config.conf
root      831900       1  1 11:41 ?        00:00:00 /usr/local/app/tars/tarsnode/data/kk.userstatus/bin/userstatus --config=/usr/local/app/tars/tarsnode/data/kk.userstatus/conf/kk.userstatus.config.conf

**Comment by lbbniu** [comment]
怎么复现？

**Comment by manchurio** [comment]
我也偶尔会遇到这个问题,  会存在多个进程.
