### ISSUE TITLE
设置 GODEBUG=gctrace=1, 但在日志文件中没有看到gc日志

### ISSUE THREAD

**Issue by manchurio** [TarsCloud/TarsGo#450]
日志里面只有 xxx redirect stdout and stderr  to  /usr/local/app/tars/app_log//XXX/xxx/XXX.xxx.log
启动时候没看到gc相关的日志, 
但如果自己手工敲命令用 tars_start.sh 启动, 就可以在控制台看到gc日志

不知道tars是不是只是重定向了标准输出流, 没有重定向标准错物流(gc日志用标准错误流)

要怎样才能看到gc日志?

**Comment by lbbniu** [comment]
@ruanshudong tarsnode 是不是没有处理标准错误重定向

**Comment by lbbniu** [comment]
> 日志里面只有 xxx redirect stdout and stderr to /usr/local/app/tars/app_log//XXX/xxx/XXX.xxx.log 启动时候没看到gc相关的日志, 但如果自己手工敲命令用 tars_start.sh 启动, 就可以在控制台看到gc日志
> 
> 不知道tars是不是只是重定向了标准输出流, 没有重定向标准错物流(gc日志用标准错误流)
> 
> 要怎样才能看到gc日志?

您这边是通过什么方式开启的GC相关日志？ 确定开启成功了吗？

**Comment by lbbniu** [comment]
> 

方便贴出 模板核心配置 和 tars_start.sh 内容吗？

**Comment by lbbniu** [comment]
配置
<img width="489" alt="image" src="https://user-images.githubusercontent.com/6211983/234031859-8de3be2f-4844-4b7a-bb46-62645f00f8d4.png">
GC日志
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/6211983/234032417-e4868cf2-883e-4039-a8e5-7f14943c56c8.png">

没问题，先关闭了
