### ISSUE TITLE
php作为客户端发请求给go tars服务端，无法正常解析消息

### ISSUE THREAD

**Issue by khadgarmage** [TarsCloud/TarsGo#46]
tars文件：
module TestApp{
interface SayHello{
	int echoHello(string name, out string greeting);
};
};
php代码：
// 指定主控ip
$config = new \Tars\client\CommunicatorConfig();
$config->setLocator('tars.tarsregistry.QueryObj@tcp -h 10.0.2.15 -p 17890');
$config->setModuleName('App.Server');
$config->setCharsetName('UTF-8');
$servant = new \TestApp\HelloGo\SayHelloObj\SayHelloServant($config);

echo "Locator specified with default socketmode 1\n";
$name = 'ted';
$intVal = $servant->echoHello($name, $greetings);
var_dump($greetings);

**Comment by khadgarmage** [comment]
@sandyskies

**Comment by khadgarmage** [comment]
@sandyskies

**Comment by sandyskies** [comment]
The problem is caused by php ,which use iversion as requestf

**Comment by sandyskies** [comment]
use $config->setIVersion(1);  to set the iverson to 2
