### ISSUE TITLE
make 编译出错

### ISSUE THREAD

**Issue by heqiang** [TarsCloud/TarsGo#490]
根据官方文档快速开始，
![1687607324283](https://github.com/TarsCloud/TarsGo/assets/40254331/a4860e80-d6c2-4fa4-a9e4-c8d9ef4e5cfd)
直接运行main函数的话
![1687607395861](https://github.com/TarsCloud/TarsGo/assets/40254331/a50ce055-668d-44c2-97d6-74d60d1a7d51)
是我配置的问题吗？还是肿么回事啊

**Comment by lbbniu** [comment]
问题1：可能是makefile 不兼容windows环境
问题2：可以看下项目目录中的 `start.sh` 中的程序启动命令，这个报错的原因是你启动程序没有指定配置文件

**Comment by lbbniu** [comment]
> 根据官方文档快速开始， ![1687607324283](https://user-images.githubusercontent.com/40254331/248471163-a4860e80-d6c2-4fa4-a9e4-c8d9ef4e5cfd.png) 直接运行main函数的话 ![1687607395861](https://user-images.githubusercontent.com/40254331/248471430-a50ce055-668d-44c2-97d6-74d60d1a7d51.png) 是我配置的问题吗？还是肿么回事啊

第一个问题，近期会修复

**Comment by heqiang** [comment]
> > 根据官方文档快速开始， ![1687607324283](https://user-images.githubusercontent.com/40254331/248471163-a4860e80-d6c2-4fa4-a9e4-c8d9ef4e5cfd.png) 直接运行main函数的话 ![1687607395861](https://user-images.githubusercontent.com/40254331/248471430-a50ce055-668d-44c2-97d6-74d60d1a7d51.png) 是我配置的问题吗？还是肿么回事啊
> 
> 第一个问题，近期会修复

噢噢 好的
