### ISSUE TITLE
How to solve the problem that the frame keeps reporting errors under win10?

### ISSUE THREAD

**Issue by mingjiana** [TarsCloud/TarsGo#500]
Usage

  cmake [options] <path-to-source>                      
  cmake [options] <path-to-existing-build>              
  cmake [options] -S <path-to-source> -B <path-to-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'cmake --help' for more information.

**Comment by lbbniu** [comment]
Recommend using macOS or Linux environment.
