### ISSUE TITLE
你们的tars2go工具太糟糕了

### ISSUE THREAD

**Issue by duguying** [TarsCloud/TarsGo#66]
1.
```batch
tars2go -outdir TestApp\HelloGo\tars -I TestApp/HelloGo/tars TestApp\HelloGo\tars\SayHello.tars
```
期望生成的是所有的 *_IF.go 放在TestApp/HelloGo/tars下，结果变成了TestApp/HelloGo/tars/TestApp
默认直接放到了TestApp/HelloGo下，那我要是有100个tars文件那你岂不是要在我的项目的根目录的父目录创建100个go文件，简直无法忍受。

2. 还有HelloWorld这种路径命名简直就是不能忍受，我是在写go，不是写Java，谢谢。

3. 我项目根目录上层为何要默认再加一层，如果说当作子项目还能接受。tars需要用Xxx.Xxx作为标识，但没必要逼着golang按照java的规范写。

**Comment by sandyskies** [comment]
2和3 我没太明白你说的意思，麻烦可以的话，微信详细和您了解下，微信号sandyskies

**Comment by sandyskies** [comment]
package main

import (
	"github.com/TarsCloud/TarsGo/tars"

	"TestApp"
)

func main() { //Init servant
	imp := new(SayHelloImp)                                    //New Imp
	app := new(TestApp.SayHello)                                 //New init the A JCE
	cfg := tars.GetServerConfig()                               //Get Config File Object
	app.AddServant(imp, cfg.App+"."+cfg.Server+".SayHelloObj") //Register Servant
	tars.Run()
}
这是服务端helloworld的例子，没明白你说的路径命名，我们都是通过vendor来解决的

**Comment by duguying** [comment]
@sandyskies 我个人并不觉得生成的*_IF.go应当放在vendor中，vendor一般是指第三方依赖，而*_IF.go则确实属于该项目的重要组成部分。另外，纵观golang项目import路径，很少发现有项目以大驼峰的形式来命名，TestApp/HelloGo这种路径还是很不大众的。

**Comment by sandyskies** [comment]
@duguying  你说的驼峰问题，可以讨论下。 vendor的话，可以不放，但import 就必须相对路径
