### ISSUE TITLE
cannot use buf (type []byte) as type []int8 in field value

### ISSUE THREAD

**Issue by XingFang** [TarsCloud/TarsGo#72]
Tars/go/tars/servant.go:52:3: cannot use buf (type []byte) as type []int8 in field value
This is a problem with the go compiler or a tars file error？
env:
tarsgo 1.0
go 1.11.2
tars2go 1.0

**Comment by sandyskies** [comment]
Hi, This is becuase ,Tars2go tool version is not  compatible with tars2go framework ， please update both.
go get -u github.com/TarsCloud/TarsGo/tars
go install $GOPATH/src/github.com/TarsCloud/TarsGo/tars/tools/tars2go

**Comment by sandyskies** [comment]
@XingFang
