### ISSUE TITLE
example中配置错误

### ISSUE THREAD

**Issue by glymehrvrd** [TarsCloud/TarsGo#74]
https://github.com/TarsCloud/TarsGo/blob/master/examples/EchoTestServer/EchoTestServer.conf
root是taf，导致加载不了配置

**Comment by sandyskies** [comment]
ok,可以提个pr修复下，改成tars

**Comment by sandyskies** [comment]
@glymehrvrd  也建议在管理平台部署

**Comment by jchalex** [comment]
Thanks for your tips, this bug has been fixed in commit d966cc7ec5b8700f9f42a3d7ccbf53eb10c67b7a.
