### ISSUE TITLE
 多个Servant可以共享同一套IP端口吗？

### ISSUE THREAD

**Issue by chenyahui** [TarsCloud/TarsGo#87]
Tars中每个Servant似乎都是独立的IP和端口。如果想把服务接口分割成多个Servant，每个Servant负责少量的服务接口。这样的话似乎并不是太友好。 

多个Servant可以共享同一套IP端口吗？

**Comment by glymehrvrd** [comment]
应该不可以，底层是根据port对servant进行路由的

**Comment by sandyskies** [comment]
不行的，servant是用来寻址IP 和port的
