### ISSUE TITLE
Print function logger does not print function name

### ISSUE THREAD

**Issue by bigobject** [TarsCloud/TarsGo#91]
Look at the print function. In debug mode, you can print out the file name and line, but not the function name. Because some file names may be the same in the project, it is not a good for trouble -shooting problem. Please add  function name to be printed.
The following code is where you can see the name and line number of the printed file
#/tars/util/logger/logger.go
if logLevel == DEBUG {
_, file, line, ok := runtime.Caller(2)
If! OK {
File =???
Line = 0
} else {
file = filepath.Base(file)
}
fmt.Fprintf(buf, "%s:%d|", file, line)
}
It is suggested to amend it to
227         if logLevel == DEBUG {
228             pc, file, line, ok := runtime.Caller(2)
229             if !ok {
230                 file = "???"
231                 line = 0
232             } else {
233                 file = filepath.Base(file)
234             }
235             fmt.Fprintf(buf, "%s|%s:%d|", runtime.FuncForPC(pc).Name(), file, line)
236         }

**Comment by hooligan520** [comment]
has support
